### ISSUE TITLE
Add build cache

### ISSUE THREAD

**Issue by jeshan** [jeshan/tfbridge#1]
Project needs to download a lot of dependencies. Adding build cache may improve the build speed. Adding caching in buildspec.yml as follows doesn't seem to work:

```yaml
cache:
  paths:
    - /go/pkg/**
```

I added an s3 bucket to the codebuild configuration too to no avail. A small 162-byte file was uploaded to the bucket
